### ISSUE TITLE
Braintree and v1.94 checkout

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/paid-memberships-pro#557] opened 2017-10-30 05:07 UTC
I'm seeing some pretty interesting issues with 1.94

The discount code is showing even though no codes are loaded
The whole div for the credit card details does not load with braintree

Any suggestions?

Environment: PHP 7.1, Cpanel, LiteSpeed

**Comment by jbruggeling** [comment] 2017-10-30 05:24
Error appears to be JavaScript Related: Console is showing - 

JQMIGRATE: Migrate is installed, version 1.4.1  jquery-migrate.min.js:2:542
TypeError: jQuery(...).val(...) is undefined[Learn More]  membership-checkout:499:61
	pmpro_updateBraintreeAccountNumber https://underwater.flindersclubs.asn.au/membership-account/membership-checkout/:499:61
	<anonymous> https://underwater.flindersclubs.asn.au/membership-account/membership-checkout/:504:4

**Comment by eighty20results** [comment] 2017-10-30 10:49
Hi,

I'm going to spend some time troubleshooting Braintree this week, so will possibly be submitting pull requests against the gateway in PMPro.

**Comment by eighty20results** [comment] 2017-10-30 10:51
Off hand, I wonder if there may be issues with the fact that we're embedding JavaScript in the checkout page and not waiting until the page is ready to execute it.. 

It worked before, but perhaps we've changed the load order of the JS libraries (or Braintree did on their end) causing these problems.

**Comment by jbruggeling** [comment] 2017-10-30 11:21
Yeah worked fine in the previous version was trying to work out what has changed. Apart from this 1.94 is a huge package of excellent changes / updates 👍

**Comment by concatdan** [comment] 2017-10-31 03:01
Hi, the issue seems to have been caused by:
[Merge branch 'dev'... by kimcoleman committed 12 days ago](https://github.com/strangerstudios/paid-memberships-pro/commit/eba9573a691dbbb4c22da8f850fe02c132a78b1e#diff-3bcec4ab0b4137df5df46cf6eebba2c6)

All the actual payment fields have been removed. Is there any chance of an urgent fix? This will be affecting anyone using Braintree with PMPro. Customers are screaming, etc.

Thanks for the otherwise excellent PMPro plugin.

P.S We have a PMPro Plus membership if that is relevant.

**Comment by eighty20results** [comment] 2017-10-31 03:03
There's a fix in pull request #561 that also deals with an issue in the webhook handler for Braintree.

Will be released by @strangerstudios as soon as testing is complete.

**Comment by jbruggeling** [comment] 2017-10-31 05:06
@eighty20results just a thought if your playing with Braintree to put in a way to pass the company name via the API (:company)

**Comment by jbruggeling** [comment] 2017-11-08 11:46
Happy to report 1.9.4.1 works as expected on Braintree and seeing the payment process working in a production environment.

**Comment by ideadude** [comment] 2017-11-08 16:39
> Happy to see the is ready java-script checks would like to see this more to allow for better async loading where required.

we're working on it. thanks for your patience and help fixing these Braintree bugs.

**Closed by ideadude** 2017-11-08 16:39 UTC
