### ISSUE TITLE
Failed account creation still charges card

### ISSUE THREAD

**Issue by curtismchale** [strangerstudios/paid-memberships-pro#247] opened 2015-09-30 19:15 UTC
Set up a user with a username over 60 characters. The account will NOT be created because user_login in the WP database has a limit of 60 characters.

Using the stripe gateway (haven't tested with other gateways) even though the user wasn't created the card is charged.

Ideally I'd like to see no charge made when this happens and an email going to the side admin notifying them of the issue with some information on the user.

Looks like we'd need to change the order of processing then from processing the payment first to processing the user first and then only charging if a proper user account was created.

**Comment by strangerstudios** [comment] 2015-10-30 13:53
In this specific case, could we not just check for a valid username before proceeding?

> Looks like we'd need to change the order of processing then from processing the payment first to processing the user first and then only charging if a proper user account was created.

This would be a big change, and there are a lot of reasons to accept payment first before setting up the user.

**Comment by curtismchale** [comment] 2015-10-30 17:12
Yeah I looked at it and it would be a big change for sure. It really means flipping the whole order processing sequence around so that processing happens first.

What are all these reasons that we should charge first and create user later?

From a user perspective I'd be more annoyed if I got charged and had an account but the charge didn't go through.

I can see from the site admin end that they'd rather have the money so the user didn't get cold feet and say no, but I'd typically stick with the user needs on things like this.

**Comment by strangerstudios** [comment] 2015-12-03 15:47
pinging this because we should still check for the user login count before processing.

RE why charge and then create the user: In general, errors with payment (declined CCs, fraud detection, etc) happen more frequently than errors with generating the user account after payment goes through. 

Also, we did choose here to favor the site owner to not create a user account until the payment goes through. We could have created the user, then processed payment, then changed the user's membership level (PayPal Standard works this way) but a lot of sites are setup so that logged in users have access to things they don't want them to have access to without paying. We definitely think they should use membership level controls so non-members users don't have access, but lots of folks don't anticipate it to work that way and it's kind of an education issue.

Hope that makes sense.

**Comment by MKWeb2** [comment] 2015-12-05 11:57
@strangerstudios So a user account could be created, but the actual membership access would not be granted unless the payment went through and was confirmed?

**Comment by mathieuhays** [comment] 2016-02-25 16:57
I've done a fix on one of my installations for a similar use case.
https://gist.github.com/mathieuhays/6298e2bdc8d127ec3c3a

I haven't doubled check if it fixes your use case but it worked for me.
Let me know if you want me to do a pull request on that

**Comment by strangerstudios** [comment] 2017-10-20 20:06
Hmmm... We sanitize the username coming in using sanitize_user similar to that gist:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/preheaders/checkout.php#L219

So I don't think issue should come up. In core PMPro now, it will strip the bad characters and create the user with the cleaned version. The gist Mathieuhays shared will throw an error and allow the user to change the username... which might be more preferred.

**Comment by dparker1005** [comment] 2024-03-25 15:52
Closing as payments are now only attempted after a user has been successfully created.

**Closed by dparker1005** 2024-03-25 15:52 UTC
