### ISSUE TITLE
Support "ApplePay" with Stripe

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#698] opened 2018-05-29 11:11 UTC
There has been a request for "ApplePay" with Stripe and Paid Memberships Pro.

**Comment by ideadude** [comment] 2018-11-29 18:12
Dupe of https://github.com/strangerstudios/paid-memberships-pro/issues/626

**Closed by ideadude** 2018-11-29 18:12 UTC
Labels: Difficulty: Hard, Status: Needs Thought, Type: Enhancement
