### ISSUE TITLE
"Message Confirmation" visual editor strips paragraph or break tags in Email Confirmation sent to a member

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/paid-memberships-pro#2022] opened 2022-04-11 10:41 UTC
**Describe the bug**
Text added to the message confirmation area of the edit level settings page shows in the email confirmation sent to a member without the paragraphs added in visual mode.

**To Reproduce**
1. Go to the Edit Level Settings page for any membership level
2. Add two sentences with two paragraphs to the editor in "Visual Mode"
3. Save, and send a test email confirmation template or checkout on this level
4. See the sentence in the email sent to the member outputted as one paragraph instead of two

**Screenshots**
<img width="1101" alt="Screen Shot 2022-04-11 at 11 45 29" src="https://user-images.githubusercontent.com/25005583/162715803-f6f6443d-115a-4548-bf5a-294fea1e01ec.png">

<img width="674" alt="Screen Shot 2022-04-11 at 11 37 24" src="https://user-images.githubusercontent.com/25005583/162715865-5a9bb5d6-d1df-43c8-ba83-40e2a33ef908.png">

**Expected behavior**
Paragraphs should not be stripped in the email. if you switch to a text editor, however (screenshot below), then save without switching back to visual, the first paragraph is not stripped in the email.
<img width="1029" alt="Screen Shot 2022-04-11 at 12 31 20" src="https://user-images.githubusercontent.com/25005583/162722374-1e2c947f-3698-483d-873c-f176cd6706cd.png">

<img width="685" alt="Screen Shot 2022-04-11 at 12 27 36" src="https://user-images.githubusercontent.com/25005583/162722232-666ae14c-3f3a-443f-b475-cacc9e3f63ab.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
- WordPress Version | 5.9.3
- Memberlite Version | 4.5.2
- PHP version | 7.4.28
- Paid Memberships Pro | Version 2.7.5
</details>

**Comment by kerijacoby** [comment] 2022-04-20 19:29
Noting here the customer sent a video of what they're experiencing:
https://user-images.githubusercontent.com/30249621/164308104-5c09ba9c-bc50-4e8c-b4c9-f4dcf9557d92.mov

**Comment by mircobabini** [comment] 2022-05-05 09:06
This is more related to how Classic Editor (TinyMCE) handles some tags. Since Classic Editor has an option to auto add paragraphs (wpautop), it strips any p tags added by user. This is not something we want to deal with, it's more WP Core related.

**Probably the issue is that we are not calling `wpautop` on the field value when sending the email.**

**Comment by bethgee** [comment] 2023-07-19 20:41
Is there a solution for this though??

**Comment by kimcoleman** [comment] 2023-08-17 10:05
Hi @bethgee - this was resolved in PMPro 2.12. If you are still experiencing the issue, please submit a support request either via our website or the WordPress.org support area.

I am closing this issue as completed now.

**Closed by kimcoleman** 2023-08-17 10:05 UTC
