### ISSUE TITLE
Recurring Subscription

### ISSUE THREAD

**Issue by Leinad4Mind** [strangerstudios/paid-memberships-pro#769] opened 2018-10-17 16:45 UTC
Hi there, I've Recurring Subscription in my level, 1 year subscription.
And "Auto-Renewal Optional?" to Yes, default checked.

And I didnt ticked the "Membership Expiration" option.

The problem is: On membership checkout page, when an user is prompted to pay the level he will have an option "Would you like to set up automatic renewals?" and if the user ticket that option and pays with paypal express, then its all good.

The problem is when the user untick the option and pays. It will be added to the Level, but he will not have an expiration date and therefor will never be removed...

I know that If I had ticked the membership expiration, then the user would have an expiration date, BUT since I'm using recurring subscription I dont want an user to be removed from the level when his recurring subscription is active and working just because the expiration date was acheived.

So the solution would be to fix the recurring subscription addon in order to add an expiration date when the user selects to pay without the recurring subscription. That way those users would have an expiration date set to 1 year (the time I choose for the subscription) and the ones that accepts the subscription will not get an expiration date and they'll still be removed by the gateway.

**Comment by eighty20results** [comment] 2018-10-17 17:48
IIRC, if your default definition for the membership level is _with_ an expiration configured, the add-on will remove that expiration when the user selects to auto-renew.

It would be difficult to set an expiration date in the add-on without the level having been defined with one (would have to guess) and using the approach you suggest seems to add what amounts to unnecessary complexity to the add-on when there is a pretty straight forward solution available. 

I _would_, however, agree that the whole "how to configure this add-on" could probably be documented a bit better..? (But that Issue belongs in the Issue list for the add-on).

**Comment by Leinad4Mind** [comment] 2018-10-17 17:57
It was told to me by Andrew that when using auto-renew addon I should not enabled the expiration date because the user would be automatically expired. And I've even tested to have it enabled but then my users were removed from the level, with an active subscription.

And Jason also told me this: "Setup the level with a recurring fee. Leave the expiration unchecked. Set the level to show the auto renewal checkbox.
The autorenewal checkbox add on basically swaps the billing period for the end date."

It would not "guess" the date. It will just do what jason said, using the billing period and set the expiration date (today + billing period = expiration date) and thats it.

**Comment by Leinad4Mind** [comment] 2018-10-17 18:07
And you're right I should have created the issue on the addon page, my bad.

Anyway, I've found this:
	if(!$autorenew) {
		//setup expiration
		$level->expiration_number = $level->cycle_number;
		$level->expiration_period = $level->cycle_period;

		//remove recurring billing
		$level->billing_amount = 0;
		$level->cycle_number = 0;
	}

Maybe that if isnt working as it should...

Maybe 	if(!$autorenew || $autorenew == 0) {  would do the trick?

**Comment by andrewlimaza** [comment] 2018-10-18 12:28
Just for clarification here, you would setup your membership level to never expire and set it up as recurring.

When the user does not select the auto-renew option on checkout, this Add On will change the the user's membership level to expire on the next payment date and vice-versa.

If you need further assistance, please open a thread up on our official support helpdesk at www.paidmembershipspro.com as this is a premium Add On.

I hope this clears things up.

**Comment by andrewlimaza** [comment] 2018-10-18 12:30
> Maybe if(!$autorenew || $autorenew == 0) { would do the trick?

If you adjust the code to this, does it solve your problem? We would need to test this further and try to recreate the issue on our ends.

**Comment by Leinad4Mind** [comment] 2018-10-18 13:05
It didnt solved, the autorenew was always 0 when not selected and it should really change the users membership level to expire, but it stays always as Never. 

But I've applied now this PR: https://github.com/strangerstudios/pmpro-auto-renewal-checkbox/pull/6

It seems to be it. I'll let you know.

**Comment by Leinad4Mind** [comment] 2018-10-23 09:09
It still didnt work... 
https://i.imgur.com/M1ey1GG.png

Something is happening after this code... because for what I've debug at auto-renewal, it should work. I can't see nothing wrong on that code. But maybe after the end date is being altered.

**Comment by CrandellWS** [comment] 2018-10-23 17:16
I am not using https://github.com/strangerstudios/pmpro-auto-renewal-checkbox but from my experience with the pmpro addons you might need define $autorenew as a global before you run your code...

     global $autorenew;

...

	if(!$autorenew) {
		//setup expiration
		$level->expiration_number = $level->cycle_number;
		$level->expiration_period = $level->cycle_period;

		//remove recurring billing
		$level->billing_amount = 0;
		$level->cycle_number = 0;
	}

...I could be totally off base I am just throwning my first 2 cent thought in ...

**Comment by Leinad4Mind** [comment] 2018-10-23 20:49
Since I am having this bug for more then a year now, I'll take those 2 cents.

**Comment by eighty20results** [comment] 2018-10-23 20:56
`$autorenew` isn't a global variable and making it one, since it's being defined [here](https://github.com/strangerstudios/pmpro-auto-renewal-checkbox/blob/master/pmpro-auto-renewal-checkbox.php#L213-L222) before it is used [here](https://github.com/strangerstudios/pmpro-auto-renewal-checkbox/blob/master/pmpro-auto-renewal-checkbox.php#L224) doesn't appear to change anything, sorry.

**Comment by CrandellWS** [comment] 2018-10-24 01:29
Maybe you can make it "pmpro_cancel_on_next_payments_date"

https://gist.github.com/strangerstudios/6169167 

Good luck Let me know I would like to use the checkbox

**Comment by TarantinoMariachi** [comment] 2018-10-24 01:31
I was already using that, orelse I would have another problem xD

**Comment by Leinad4Mind** [comment] 2018-10-24 01:33
I am already using that. If I wasnt, then I would have another problem.

**Comment by eighty20results** [comment] 2018-10-24 04:10
Having stepped through the Auto Renewal add-on code, line by line, for a recurring membership level checkout, with a debugger, for the Stripe, Authorize.net and PayPal Express payment gateway integrations, I can't reproduce a blank end date for the membership when the auto-renewal checkbox un-checked. (Every time I run through it, the end date gets configured)...

Maybe there is some other add-on/plugin on your site(s) that also changes the end-date based on the membership level? (Like, for instance [the one referenced above](
https://gist.github.com/strangerstudios/6169167)?)

**Comment by Leinad4Mind** [comment] 2018-10-24 09:01
I'm using these addons:

Paid Memberships Pro - Advanced Levels Page Shortcode Add On (2.4)
Paid Memberships Pro - Auto-Renewal Checkbox (2.5)
Paid Memberships Pro - Better Logins Report Add On (2.3.2)
Paid Memberships Pro - Email Templates Add On (0.7.1)
Paid Memberships Pro - Failed Payment Limit Add On (0.2)
Paid Memberships Pro - MailChimp Add On (2.1.1)
Paid Memberships Pro - Member History Add On (2.4.2)
Paid Memberships Pro - Register Helper Add On (1.4)
Paid Memberships Pro - Subscription Check Add On (0.2)

PMPro Customizations ( https://pastebin.com/9UKJaR9Q  )

Do you see any addon I should be looking deep, that could cause the problem?

**Comment by CrandellWS** [comment] 2018-10-24 19:43
I went ahead and installed and tested the checkbox plugin which did in fact add an expiration date box/y unchecking the box

also what about discount codes??

> If a customer uses a discount code, the auto renewal checkbox will be ignored and the default recurring billing settings from the discount code will be used.

**Comment by Leinad4Mind** [comment] 2019-02-01 15:21
After installing the last versions of addons and pmpro, this bug was finally solved! Thanks god! 

Just letting you guys know.

**Comment by kimcoleman** [comment] 2019-02-01 16:22
Excellent - I'm going to close this issue. If another commenter would like it to remain open please let me know.

**Closed by kimcoleman** 2019-02-01 16:22 UTC
