### ISSUE TITLE
Error: Stripe - Email Notification - "Could not cancel old subscription."

### ISSUE THREAD

**Issue by woodwardmatt** [strangerstudios/paid-memberships-pro#639] opened 2018-02-14 04:08 UTC
I've just rolled out the latest version of PMPRO (v1.9.4.3 on WP v4.9.4) and was testing membership level changes. I noticed that when I change plan I have consistently gotten the following email sent through:

> There was an error canceling the subscription for user with ID=<ID removed>. You will want to check your payment gateway to see if their subscription is still active.
>
> Error: Could not cancel old subscription.
> User Email: <Email removed>
> User Display Name: <Name removed>
> Order: EC8E2033BC
> Gateway: stripe
> Subscription Transaction ID: sub_CJtKk3WGHJj6z1

Having checked the gateway, the subscription is being cancelled correctly, and the new subscription created etc. The membership is also being updated correctly locally in pmpro. Thinking this may be a false positive of sorts. I have only started seeing this since upgrading to 1.9.4.3 but can't see file changes directly that would contribute to the issue in that release. 

@ideadude - Had any other reports of this behaviour?

**Comment by woodwardmatt** [comment] 2018-02-14 04:09
**Note**: I've removed any identifiable data from the email example :)

**Comment by woodwardmatt** [comment] 2018-02-15 07:38
Quick update - I've also observed this being sent when an overdue customer cancels their subscription. Yet both the payment gateway an pmpro subscriptions are actually cancelled fine.

**Comment by woodwardmatt** [comment] 2018-02-19 04:31
Another scenario today - Customer cancels - we dont get any pmpro cancellation email, just the error above, yet both the payment gateway and pmpro membership details are in tact. 

Have a feeling this customer may be an edge case, as their subscription in stripe seemed a little incomplete and the web hook from stripe hit a 400 error of "You cannot use a Stripe token more than once: <Token Removed>."

**Comment by eighty20results** [comment] 2018-02-19 12:51
Hi Matt,

Just wanted you to know I'm working on isolating this overall issue this week. My initial theory is that for some reason we're triggering the code twice (which is why the email is sent).

The first time we correctly cancel the membership and clean up on Stripe. 

The second time, we obviously have nothing to do, so we think it's an error condition and notify the admin (incorrectly).

**Comment by woodwardmatt** [comment] 2018-02-20 03:06
Thanks Thomas ( @eighty20results ) really appreciate the heads up :) 

Could the second call be related to Stripe making a call back to pmpro to notify of the cancellation maybe? (Even though pmpro likely notified Stripe to start with?). Just a thought :)

I'll update the thread if I spot anything more from my side :)

**Comment by ideadude** [comment] 2018-03-01 01:15
That email is sometimes a false positive. But you would sometimes get it in cases where PMPro and Stripe were out of sync and PMPro couldn't find the subscription to delete.

However, we have had bugs where this email was going out when it shouldn't have because we were trying to cancel the subscription twice (or more). So we would cancel the sub, and then try to cancel it again which would throw the error.

1.9.4.3 had one fix for this where we fixed a bug where having multiple orders for the same sub (pretty common) would cause us to try to cancel for each order instead of once.

I've heard of people still having issues and am trying to figure out what might be causing it.

How are you changing users when the error occurs? Can you reproduce it reliably? If so, let us know the exact steps. Thanks.

**Comment by woodwardmatt** [comment] 2018-03-01 09:49
@ideadude thanks for the info Jason. I've just gone through and cancelled a few test accounts but haven't seen the email just yet. 

I'll run through a few of the scenarios I saw it occur under above and see what I can recreate consistently and report back.

**Comment by positivejam** [comment] 2018-04-21 23:32
Thanks for looking into this, folks. I am having this issue as well. Any updates?

**Comment by woodwardmatt** [comment] 2018-04-23 10:00
@positivejam think this was resolved in one of the last updates, are you on the latest version?

**Comment by positivejam** [comment] 2018-04-24 00:04
Yeah, I'm on 1.9.4.4. I haven't been able to reproduce it myself yet, I just have second-hand reports (since installing 1.9.4.4) from my site owner that he's getting the "There was an error canceling the subscription..." email. Then I check the subscription in Stripe and it's in fact canceled.

**Comment by ideadude** [comment] 2018-09-06 20:37
We resolved one flavor of this, but I'm seeing another.

If a Stripe subscription is cancelled on the Stripe side, perhaps because the 3 failed payment limit is reached, then it will send a customer.subscription.deleted webhook message. PMPro will process this and then cancel the user's membership here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/stripe-webhook.php#L316

All good so far. However, during the cancel, it will try to cancel the subscription at the gateway, get the 404 from Stripe and then return an error here.

If the cancel originates in WP, this is okay. But if the cancellation originates in Stripe, we're going to get a false positive here. We should check somehow if this cancellation is part of a webhook processing before trying to cancel at the gateway.

We could set a global flag, or check for the Stripe event parameter.

**Comment by ideadude** [comment] 2018-09-06 20:40
Follow up. I don't think it's enough to just check if $_REQUEST['action'] == 'stripe_webhook' because there may be cases where other webhook messages kick off a subscription cancel/etc that we do want to send back to Stripe.

We can save some status on the event into a global var to check.

**Comment by ideadude** [comment] 2022-06-08 12:28
We have recently made several updates that address these types of issues. I'm going to close this issue, but if you are still experiencing cases where you get this email when you shouldn't... or otherwise have issues with cancellations being sync'd properly. Please open a new issue. Thanks.

**Closed by ideadude** 2022-06-08 12:28 UTC
Labels: Status: Needs Code, Status: Need to Recreate
